services:
  envelope-api:
    build:
      context: .
    container_name: envelope-api
    hostname: envelope-api
    depends_on:
    - envelope-db
    ports:
    - "8080:8080"
    volumes:
    - ./application.properties:/app/application.properties:ro
    environment:
      DB_URL: jdbc:postgresql://envelope-db:5432/${ENVELOPE_DB}
      PG_USER: ${ENVELOPE_USER}
      PG_PASSWORD: ${ENVELOPE_PASSWORD}
  envelope-db:
    image: postgres:16.4-alpine
    container_name: envelope-db
    hostname: envelope-db
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ENVELOPE_USER}
      POSTGRES_PASSWORD: ${ENVELOPE_PASSWORD}
      POSTGRES_DB: ${ENVELOPE_DB}
volumes:
  pgdata:
